### ISSUE TITLE
Wrong raid durations

### ISSUE THREAD

**Issue by nickmhc** [MonkeyTedBaker/Monocle#14]
Possibly related to the problem with eggs being ignored... just not sure where the webhook standard deviates. Anyhow, they raid notifications are showing as two hours from start to end instead of just one

Could also be a PokeAlarm issue where the default time in the time_str array is + 2 hours

**Comment by evilmoses** [comment]
See PR...

**Comment by nickmhc** [comment]
Fixed and closed
