### ISSUE TITLE
Exclude black list or choice of using other predefined lists to avoid injection of Pokemon into sightings table.

### ISSUE THREAD

**Issue by XGrendelX** [MonkeyTedBaker/Monocle#21]
Create a new config option in Monocle that would ignore and exclude listed pokemon from ever being injected into the sightings table in the first place.  Large maps would benefit from this feature as it would allow for smaller db tables and potentially less faults with the database. Also it could help with performance since the filtering happens before the data even reaches the database.

**Comment by XGrendelX** [comment]
Other predefined list might be the Trash ID's or so on since that function would be useless anyway if they were excluded before they even reached the database.

**Comment by Avatar690** [comment]
My forks do this already.  If you want it monkey I'll send the mod over.

**Comment by beloware** [comment]
Looks Monkey now a bit away. But i give this a +1 vote.

**Comment by Avatar690** [comment]
Guess Ill make the PR

**Comment by XGrendelX** [comment]
Thanks for making a PR addressing my request.  Enjoying the testing of it on my maps!

**Comment by XGrendelX** [comment]
Thanks again to Avatar690's PR 25 which was merged.
