### ISSUE TITLE
Not working with "SPAWN_ID_INT = False" in config

### ISSUE THREAD

**Issue by almico** [MonkeyTedBaker/Monocle#35]
I just cloned Monocle from scratch and scan.py is logging this (basically blocking) error:

```
[2017-10-01 09:42:26][   ERROR][dbprocessor] A wild TypeError appeared in the DB processor!
Traceback (most recent call last):
  File "/root/pogo/Monocle-monkey/monocle/db_proc.py", line 55, in run
    if (spawn_id > 0 and (spawn_id not in spawns.updated_at or spawns.updated_at[spawn_id] < (time() - 21600))):
TypeError: '>' not supported between instances of 'str' and 'int'
```

In config I set

```
SPAWN_ID_INT = False
```

As per the latest PGScout recommendation.
I cannot run scan.py at the moment.

**Comment by almico** [comment]
From Discord:

![image](https://user-images.githubusercontent.com/15247405/31052894-ba9d515e-a690-11e7-994c-fdfbc2b1251d.png)

**Comment by almico** [comment]
I think the solution should be, in db_proc.py on line 55, to replace:

```
spawn_id > 0
```

with something like:

```
(spawn_id != (0 if conf.SPAWN_ID_INT else 'LURED'))
```

**Comment by phonezawphyo** [comment]
This is non-issue. Change your data type of spawn_id to int. It is not supposed to be string. Gotta day official Monocle is wrong on this one.

**Comment by MonkeyTedBaker** [comment]
Do not listen to sloppy drive. spawn_id will stay int in my fork. I will re move spawn_id_int flag.
And you do not need to change spawn_id to string. It will work just fine with int.
In return, I will provide a conversion to string just for sending request to pgscout.
Meanwhile, do not use the new version of pgscout.

I have my reasons for this. We can discuss in details in #monkey if you are not satisfied.
