### ISSUE TITLE
Unusable setup (lots of IntegrityErrors)

### ISSUE THREAD

**Issue by almico** [MonkeyTedBaker/Monocle#38]
Hello,
This is the branch I am working on (I trashed everything and started from scratch a few days ago):

```
[root@server Monocle-monkey]# git branch
* develop
```

This is MySQL version I am using:

`
mariadb-server-5.5.56-2.el7.x86_64
`

I am running `CentOS Linux release 7.3.1611 (Core)`.

I ran:

`
git pull
`

Then deleted all tables and ran:

`
alembic upgrade head
`

At first I tried to restore spawnpoints records from the backup, but got IntegrityErrors, therefore I trashed everything again, reran alembic and still got the same errors as soon as I ran:

`
python3.6 scan.py --no-pickle --bootstrap
`

These are the errors I see in scan.log:

```
[2017-10-04 09:19:15][   ERROR][dbprocessor] A wild IntegrityError appeared in the DB processor!: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`monoclepglargemonkey`.`fort_sightings`, CONSTRAINT `fort_sightings_ibfk_1` FOREIGN KEY (`fort_id`) REFERENCES `forts` (`id`))')
```

I'm stuck 😭

**Comment by MonkeyTedBaker** [comment]
This #37 should fix your problem.
Get the latest code from `MonkeyTedBaker/develop` and run scan.py with `--no-pickle` once.

**Comment by almico** [comment]
So:

- `git pull`
- `alembic upgrade head`
- restore of spawnpoints from the backup
- `python3.6 scan.py --no-pickle`

Should fix the issue?

**Comment by phonezawphyo** [comment]
yes

**Comment by almico** [comment]
Restoring spawnpoints led to this kind of errors:

```
[2017-10-04 09:43:24][   ERROR][overseer] A wild TypeError appeared while updating spawns!
Traceback (most recent call last):
  File "/root/pogo/Monocle-monkey/monocle/overseer.py", line 339, in update_spawns
    await run_threaded(spawns.update)
  File "/root/pogo/Monocle-monkey/monocle/shared.py", line 80, in run_threaded
    return await LOOP.run_in_executor(x, cb, *args)
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/pogo/Monocle-monkey/monocle/spawns.py", line 65, in update
    spawn_time = (spawn.despawn_time + 1800) % 3600
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

**Comment by almico** [comment]
I am forced to trash everything and bootstrap again, I guess...

**Comment by MonkeyTedBaker** [comment]
Yeah. Data in your DB is very inconsistent, probably due to too much manual intervention of pickles and DB. So, it would be the best to wipe the db (including spawnpoints) and redo bootstrap.
It takes only a few hours in Monocle anyway.

You will not likely be needing to touch pickles and DB by hand from now, I made it very stable with the latest PR.

**Comment by almico** [comment]
Ok. Deleted all tables. Restored nothing and bootstrapped again.
I have never touched pickles and the only thing I did on the db was restore spawnpoints table using standard mysql tools.
I never ran any ALTER TABLE or anything else.

**Comment by almico** [comment]
Anyway... Since I read that some spawnpoints should now no longer exist (after the event), I will take advantage of this to recreate them all 😆

**Comment by MonkeyTedBaker** [comment]
Don't forget to close this when you are satisfied. :)

**Comment by almico** [comment]
Will do 😄 
Interesting! Now I finally see some names and urls in the forts table. Great!
