### ISSUE TITLE
Accounts with reason "warn" are put back into rotation when instance is restarted

### ISSUE THREAD

**Issue by almico** [MonkeyTedBaker/Monocle#73]
I had to restart multiple times Monocle during the past 12 hours (because of logging errors, captchas, and some other reasons) and every time Monocle put back into rotation warned accounts. This means that every time it spent really a lot of time just to discover that those accounts had been identified as "warn" just a few minutes before (before restarting).
At the moment Monocle is trying to figure out that 300 accounts were already marked as banned no more than 10 hours ago 😆
I am running swapin cron task.

**Comment by MonkeyTedBaker** [comment]
this may sound like I'm in denial, but there is no such issue. it was carefully handled in order not to have such problems. pls check carefully and bring proof.

**Comment by almico** [comment]
I am not sure I know the expected behaviour here.
How long should warned accounts be kept in warned state before reusing them?
Yesterday I had 200 warned accounts and all of them were brought back into rotation. Most of them are now again in warn state and (I think) some of them received code 3.
Since yesterday all warned were brought into rotation, all current warned accounts should remain in warned state if I restart Monocle.
Is this correct?

**Comment by almico** [comment]
And does "--no-pickles" make any difference?
I'm asking because I think I need to bootstrap again because of unexpected Monocle exits (loggin errors, captchas and something else).

**Comment by almico** [comment]
I just restarted using "--bootstrap" and warned accounts were left untouched.
I will reopen this issue if and when I will find a pattern.
Thank you.
